### ISSUE TITLE
Missing setupData

### ISSUE THREAD

**Issue by kennymc-c** [splattner/goucrt#34]
I can successfully setup the denonavr integration with the remote but the json config file doesn't seem to get written into the config directory no matter if I use the default /app/ucconfig or set a different folder via the env variable. It's not a problem with Docker volume mapping since the json is already missing in the container itself.

**Comment by splattner** [comment]
The JSON file wil lbe created on first setup and is not yet there in the container image. Therefore the folder should be writable. Therefore in my Dockerfile I 'chown` the folder to the created `nonroot` user, see https://github.com/splattner/goucrt/blob/main/build/Dockerfile#L18
Do you mount e volume to your config directory? If yes, can the `nonroot` user write into that directory? 
You can also start the client with `--debug` then you should see, if there was a write error when setting up the integration.

The change with the user I made only recently, but this should already be in the v0.1.6 release. Since then, I made some other changes to the DenonAVR Client (to show media_image url e.g.), let me release that version.

**Comment by splattner** [comment]
ah and by default the config directory is set to `./ucconfig/` see https://github.com/splattner/goucrt#environment-variables and also in Code https://github.com/splattner/goucrt/blob/main/pkg/cmd/ucrt/ucrt.go#L91 
Not as the Dockerfile might suggest the `/app/ucconfig` folder. I have to document this better or even change the documentation there to not mislead

**Comment by kennymc-c** [comment]
Seems to be a permission problem. The nonroot user can not write into /app. Strange, since I mounted the volume with rw access -v '/mnt/user/appdata/goucrt/':'/app/ucconfig/':'rw' . Without the volume mapping I can write into the ucconfig directory

**Comment by splattner** [comment]
What are the permissions for `/mnt/user/appdata/goucrt/`? and how does it look in the container when the volume is mounted? Is /mnt/user some mounted directory (nfs, smb or similar)? I guess the permission there are not set correctly and maybee if its a mount on your host, docker cannot really change or mount with the correct permission

This is how it looks on my side. `localdir` is a local path on my docker host.

Start the container with:

```
docker run -v ./localdir:/app/ucconfig ghcr.io/splattner/goucrt:v0.1.7 denonavr
``` 

Inside the container:
```
/app $ ls -al
total 10764
drwxr-xr-x    1 root     root          4096 Oct 15 17:21 .
drwxr-xr-x    1 root     root          4096 Oct 16 08:00 ..
drwxrwxr-x    2 nonroot  nonroot       4096 Oct 16 08:00 ucconfig
-rwxr-xr-x    1 root     root      11010048 Oct 15 17:21 ucrt
```

Outside on the docker host:

```
ls -al
drwxrwxr-x 12 sebastian sebastian     4096 Okt 15 19:47 .
drwxrwxr-x  6 sebastian sebastian     4096 Okt  5 07:57 ..
drwxrwxr-x  2 sebastian sebastian     4096 Okt 16 10:00 localdir
```

And with this, I can write to `/app/ucconfig`, no problem there

**Comment by kennymc-c** [comment]
I solved it by setting write permission for every user for the folder in /mnt/user/appdata/goucrt/. Usually this folder automatically gets created with the user nobody that is in the also users group by my Docker implementation for Unraid. Since the nonroot user has It's own group it probably didn't work.
